// Segment data
const segmentData = {
  intellimed: { icon: '🏥', color: '#d4f5e2', industry: 'Healthcare', brand: 'IntelliMed', tagline: 'Smart Healthcare Management for Modern Clinics & Practices', status: 'dev', statusText: 'In Development', overview: 'IntelliMed is Scholarstix\'s AI-powered healthcare management platform designed specifically for independent clinics, GP practices, specialist rooms and community health facilities across Africa. It replaces disjointed paper-based and legacy systems with a unified, intelligent platform that puts patient care first and administrative burden last.', features: ['Patient registration & digital records','Appointment scheduling & reminders (SMS/Email)','AI-assisted diagnosis support & symptom triage','Prescription management & drug interaction alerts','Billing, medical aid claims & payment tracking','Staff & practitioner scheduling','Secure patient communication portal','HPCSA compliance documentation support','Reporting & clinic performance analytics','Multi-branch practice management'], platform: 'Android 14+ · Web Dashboard', market: 'GP Practices, Clinics, Specialists', model: 'SaaS Subscription' },
  supersentrix: { icon: '🛒', color: '#d5e9ff', industry: 'Supermarket Retail & Wholesale', brand: 'SuperSentrix', tagline: 'AI-Powered POS & Inventory Intelligence for Retailers', status: 'live', statusText: 'Live — Beta Testing Now', overview: 'SuperSentrix is Scholarstix\'s flagship retail intelligence platform, purpose-built for independent supermarkets, spaza shops, bottle stores with retail, and wholesale operators. The SuperSentrix POS Android app gives store owners real-time operational command from a single smart device — replacing manual stock books, paper receipts and disconnected systems.', features: ['Full Point-of-Sale with receipt printing','Real-time inventory tracking & alerts','AI-driven stock replenishment recommendations','Barcode & QR code scanning support','Multi-payment: cash, card, EFT, voucher','Supplier order management','Customer loyalty & rewards programme','Daily/weekly/monthly sales reports','Multi-till & multi-branch support','Theft & shrinkage detection alerts'], platform: 'Android 14+ Mobile App', market: 'Supermarkets, Spaza Shops, Wholesalers', model: 'SaaS Subscription' },
  eventrix: { icon: '🎟️', color: '#fef3cd', industry: 'Events Management', brand: 'Eventrix', tagline: 'Complete Event Lifecycle Management — Plan, Execute, Analyse', status: 'live', statusText: 'Live — Beta Testing Now', overview: 'Eventrix is Scholarstix\'s AI-powered events management platform serving independent event planners, venues, corporate event coordinators and community organisers. The Eventrix-Go mobile Android app puts your entire event operation in your pocket — from initial concept through execution to post-event reporting.', features: ['Full event planning & task management','Digital ticketing & QR code check-in','Guest list management & RSVP tracking','Vendor & supplier coordination hub','Budget management & expense tracking','Venue & equipment booking system','AI event timeline optimisation','Sponsorship management & reporting','Staff & volunteer scheduling','Post-event analytics & ROI reporting'], platform: 'Android 14+ Mobile App (Eventrix-Go)', market: 'Event Planners, Venues, Corporate Events', model: 'SaaS Subscription' },
  memorix: { icon: '🕊️', color: '#e2f5f2', industry: 'Funeral Homes & Services', brand: 'MemoriX', tagline: 'Dignified, Efficient Funeral Service Management', status: 'dev', statusText: 'In Development', overview: 'MemoriX is Scholarstix\'s compassionate yet powerful management platform built exclusively for independent funeral homes and bereavement service providers. It handles the complex administrative, logistical and family communication needs of running a funeral business — so that staff can focus on what matters most: caring for families in their time of need.', features: ['Family & case management portal','Deceased intake & documentation workflow','Chapel, hearse & staff scheduling','Coffin & merchandise inventory management','Family communication & notifications','Invoice, payment plan & insurance billing','Burial/cremation permit documentation','Multi-location branch management','Fleet (hearse) tracking & maintenance','Regulatory compliance reporting'], platform: 'Android 14+ · Web Dashboard', market: 'Independent Funeral Homes, Mortuaries', model: 'SaaS Subscription' },
  sipspace: { icon: '🍺', color: '#ffecd2', industry: 'Liquor Trade', brand: 'SipSpace', tagline: 'Smart Liquor Retail Operations & Compliance Management', status: 'dev', statusText: 'In Development', overview: 'SipSpace is Scholarstix\'s AI-powered platform for independent liquor retailers, bottle stores and on-consumption establishments. Beyond standard POS functionality, SipSpace is built with South African liquor licensing regulations at its core — helping owners stay compliant while maximising profitability.', features: ['Liquor-specific POS with age verification','Real-time stock management by SKU/brand','Regulatory compliance tracking & alerts','Supplier order management & pricing','Sales analytics by product category','Licence renewal reminder system','Staff shift & access management','Customer loyalty programme','Theft & shrinkage monitoring','SAPS & municipality compliance reports'], platform: 'Android 14+ · Web Dashboard', market: 'Bottle Stores, Taverns, Liquor Retailers', model: 'SaaS Subscription' },
  forkflame: { icon: '🔥', color: '#fde8e8', industry: 'Pub & Meat Griller / F&B', brand: 'Fork & Flame', tagline: 'From Grill to Till — Restaurant & Pub Operations, Simplified', status: 'dev', statusText: 'In Development', overview: 'Fork & Flame is Scholarstix\'s food and beverage management platform designed for South African pubs, braai restaurants, meat grillers and casual dining establishments. It bridges front-of-house and kitchen operations into one intelligent system — reducing errors, speeding up service and increasing profitability.', features: ['Table management & reservations','Digital menu & kitchen order display','Split billing & multiple payment methods','Bar tab & running bill management','Stock & ingredient inventory control','Supplier ordering & recipe costing','Staff scheduling & tip management','Daily cash-up & Z-reading reports','Customer loyalty & repeat visitor tracking','Health & safety compliance checklists'], platform: 'Android 14+ · Kitchen Display System', market: 'Pubs, Restaurants, Meat Grillers, Braai Spots', model: 'SaaS Subscription' },
  hammertime: { icon: '🔨', color: '#ede7f6', industry: 'Builders & Hardware', brand: 'Hammer-Time', tagline: 'Hardware Store Intelligence — From Counter to Construction Site', status: 'dev', statusText: 'In Development', overview: 'Hammer-Time is Scholarstix\'s AI-powered management system for independent builders merchants, hardware stores and building material suppliers. It handles the unique complexities of hardware retail — from high-volume SKU catalogues and trade accounts to project quotations and delivery management.', features: ['High-volume product catalogue & barcode POS','Trade account & credit management','Quotation & job card generation','Supplier ordering & pricing management','Stock by category, brand & shelf location','Delivery scheduling & driver tracking','Customer project history & repeat orders','AI stock forecasting for seasonal items','Multi-branch inventory visibility','Contractor loyalty & discount programme'], platform: 'Android 14+ · Web Dashboard', market: 'Hardware Stores, Builders Merchants', model: 'SaaS Subscription' },
  gearup: { icon: '⚙️', color: '#e0e9f0', industry: 'Auto Spares', brand: 'Gear-Up', tagline: 'Auto Parts Intelligence — Workshop to Counter, Covered', status: 'dev', statusText: 'In Development', overview: 'Gear-Up is Scholarstix\'s specialist platform for independent auto spares retailers and workshop operators. It solves the unique challenges of auto parts management — massive catalogues, VIN-specific part matching, workshop job cards and warranty tracking — in one unified Android-first platform.', features: ['VIN/registration-based part lookup','Auto parts catalogue with cross-reference','Workshop job card & labour management','Parts inventory by make, model & year','Supplier ordering & back-order tracking','Customer vehicle history & service records','Warranty claim tracking & processing','Quotation & invoice generation','Cash sales & trade account billing','AI demand forecasting by vehicle type'], platform: 'Android 14+ · Web Dashboard', market: 'Auto Spares Shops, Panel Beaters, Workshops', model: 'SaaS Subscription' },
  novaroute: { icon: '🚚', color: '#e2f5f2', industry: 'Transport & Logistics', brand: 'NovaRoute', tagline: 'Fleet Intelligence & Route Optimisation for African Roads', status: 'dev', statusText: 'In Development', overview: 'NovaRoute is Scholarstix\'s transport and logistics management platform designed for independent fleet operators, courier services and freight companies across Southern Africa. It combines real-time fleet visibility with AI route optimisation to reduce fuel costs, improve delivery reliability and ensure full regulatory compliance.', features: ['Real-time GPS fleet tracking','AI-powered route optimisation','Driver management & performance scoring','Delivery scheduling & customer notifications','Fuel management & cost tracking','Vehicle maintenance scheduling & alerts','Proof of delivery (POD) capture','Load planning & freight documentation','RTMS & C-TPAT compliance support','Customer portal & delivery tracking link'], platform: 'Android 14+ · Web Dashboard · Driver App', market: 'Courier Companies, Fleet Operators, Freight Forwarders', model: 'SaaS Subscription' },
  eccoroots: { icon: '📚', color: '#e8f5e2', industry: 'Education', brand: 'Ecco-Roots', tagline: 'Empowering African Educators with AI-Driven Learning Management', status: 'dev', statusText: 'In Development', overview: 'Ecco-Roots is Scholarstix\'s educational technology platform designed for independent schools, tutoring centres, early childhood development (ECD) facilities and private training providers across Africa. It brings modern learning management capabilities to institutions that have been underserved by expensive international EdTech platforms.', features: ['Student enrolment & profile management','Attendance tracking (biometric/manual)','Timetable & classroom scheduling','AI-personalised learning progress tracking','Fee collection & payment plans','Parent communication portal (SMS/App)','Teacher & staff management','Homework & assessment management','Report card generation & distribution','SACE & DBE compliance support'], platform: 'Android 14+ · Web Dashboard · Parent App', market: 'Private Schools, Tutoring Centres, ECD Facilities', model: 'SaaS Subscription' },
  relybex: { icon: '🔧', color: '#e2f5f2', industry: 'MRO — Maintenance, Repair & Overhaul', brand: 'Relybex', tagline: 'Proactive Maintenance Management — Before Breakdown, Not After', status: 'dev', statusText: 'In Development', overview: 'Relybex is Scholarstix\'s AI-powered Maintenance, Repair and Overhaul (MRO) management platform for independent service providers, property maintenance companies, industrial facility managers and equipment servicing businesses. It shifts organisations from reactive to proactive maintenance — reducing downtime, cutting costs and extending asset life.', features: ['Asset register & lifecycle management','Planned preventive maintenance scheduling','Work order creation & technician dispatch','Parts & spares inventory management','AI predictive failure alerts','Inspection checklists & compliance logs','SLA tracking & client reporting','Technician mobile app for on-site updates','Cost-per-asset reporting & analytics','Warranty & service contract management'], platform: 'Android 14+ · Web Dashboard · Technician App', market: 'Facility Managers, MRO Service Providers, Industrial Plants', model: 'SaaS Subscription' },
  micropulse: { icon: '🏭', color: '#fde8e8', industry: 'Manufacturing Operations', brand: 'Micro-Pulse & UBOS Enterprise Suite', tagline: 'AI-Powered Production Intelligence for Modern Manufacturers', status: 'dev', statusText: 'In Development', overview: 'Micro-Pulse is Scholarstix\'s manufacturing operations management platform for small and mid-size manufacturers. The UBOS (Unified Business Operating System) Enterprise Suite extends this into a comprehensive ERP-level platform for growing manufacturers who need integrated control over production, inventory, quality, workforce and financial operations — without the cost and complexity of traditional enterprise ERP systems.', features: ['Production planning & scheduling','Bill of Materials (BOM) management','Real-time machine & line monitoring','OEE (Overall Equipment Effectiveness) tracking','Quality control & defect management','Raw material & WIP inventory control','Workforce attendance & shift management','AI demand forecasting & production planning','Customer order & delivery management','Financial reporting & cost accounting'], platform: 'Web Dashboard · Android Supervisor App', market: 'SME Manufacturers, Light Industry, Assembly Operations', model: 'SaaS Subscription / Enterprise Licence' }
};

function openSegmentModal(key) {
  const d = segmentData[key]; if(!d) return;
  document.getElementById('seg-modal-icon').textContent = d.icon;
  document.getElementById('seg-modal-icon').style.background = d.color;
  document.getElementById('seg-modal-industry').textContent = d.industry;
  document.getElementById('seg-modal-brand').textContent = d.brand;
  document.getElementById('seg-modal-tagline').textContent = d.tagline;
  const statusEl = document.getElementById('seg-modal-status');
  statusEl.textContent = d.statusText;
  statusEl.className = 'modal-status ' + d.status;
  document.getElementById('seg-modal-overview').textContent = d.overview;
  document.getElementById('seg-modal-features').innerHTML = d.features.map(f => `<div class="modal-feature-item">${f}</div>`).join('');
  document.getElementById('seg-modal-meta').innerHTML = `<div class="modal-meta-item"><div class="modal-meta-label">Platform</div><div class="modal-meta-val">${d.platform}</div></div><div class="modal-meta-item"><div class="modal-meta-label">Target Market</div><div class="modal-meta-val">${d.market}</div></div><div class="modal-meta-item"><div class="modal-meta-label">Business Model</div><div class="modal-meta-val">${d.model}</div></div>`;
  openModal('segment-modal');
}

function openModal(id) { document.getElementById(id).classList.add('open'); document.body.style.overflow = 'hidden'; }
function closeModal(id) { document.getElementById(id).classList.remove('open'); document.body.style.overflow = ''; }
function closeModalOutside(e, id) { if (e.target === document.getElementById(id)) closeModal(id); }
document.addEventListener('keydown', e => { if (e.key === 'Escape') closeModal('segment-modal'); });

// Scroll progress, back-to-top, fade-in
window.addEventListener('scroll', function() { 
  const scrollTop = document.documentElement.scrollTop; 
  const docHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight; 
  const progress = document.getElementById('scroll-progress');
  if(progress) progress.style.width = (scrollTop / docHeight * 100) + '%'; 
  const btn = document.getElementById('back-to-top'); 
  if(btn) scrollTop > 400 ? btn.classList.add('visible') : btn.classList.remove('visible'); 
}, {passive: true});

const observer = new IntersectionObserver((entries) => { 
  entries.forEach((e,i) => { 
    if(e.isIntersecting){ 
      setTimeout(() => e.target.classList.add('visible'), i*80); 
      observer.unobserve(e.target); 
    } 
  }); 
}, {threshold:0.1});
document.querySelectorAll('.fade-in').forEach(el => observer.observe(el));

// Mobile menu
function toggleMenu() { 
  const links = document.getElementById('nav-links'); 
  if(!links) return;
  const isOpen = links.style.display === 'flex'; 
  if(isOpen) links.style.cssText = ''; 
  else links.style.cssText = 'display:flex;flex-direction:column;position:absolute;top:72px;left:0;right:0;background:rgba(10,46,40,0.99);padding:1.5rem 2rem;gap:1.2rem;border-bottom:1px solid rgba(58,174,155,0.2);z-index:999;'; 
}
const navLinks = document.getElementById('nav-links');
if(navLinks) {
  navLinks.querySelectorAll('a').forEach(a => a.addEventListener('click', () => { if(window.innerWidth <= 960) navLinks.style.cssText = ''; }));
}
window.addEventListener('resize', () => { if(window.innerWidth > 960 && navLinks) navLinks.style.cssText = ''; });

// Cookie banner
function acceptCookie() { localStorage.setItem('sx_cookie', 'accepted'); const banner = document.getElementById('cookie-banner'); if(banner) banner.classList.remove('show'); }
function dismissCookie() { localStorage.setItem('sx_cookie', 'declined'); const banner = document.getElementById('cookie-banner'); if(banner) banner.classList.remove('show'); }
window.addEventListener('DOMContentLoaded', () => { if(!localStorage.getItem('sx_cookie')) { const banner = document.getElementById('cookie-banner'); if(banner) setTimeout(() => banner.classList.add('show'), 1500); } });